version: '3.8'

services:
    image: app
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        tty: true
        depends_on:
            - builder
    builder:
        image: builder
        build:
            context: .
            dockerfile: Dockerfile.builder
        working_dir: /app
