import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ------------------------------- HeroUI Setup ---------------------------------
import { create } from 'zustand'
import { Providers } from "./providers";

// Create a Zustand store for theme management
export const theme = create((set) => ({
  theme: "light",
  mode: "auto",
  toggleTheme: () => set((state) => ({ theme: state.theme === "light" ? "dark" : "light" })),
  setTheme: (newTheme) => set((state) => ({ theme: newTheme })),
  setMode: (newMode) => set((state) => ({ mode: newMode })),
}))

// -------------------------------- Component layout --------------------------------
import Header from "../components/header/page";
import Footer from "../components/footer/page";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${theme} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
