import { Fredoka } from "next/font/google";
import "./globals.css";

const fredoka = Fredoka({
  weight: '400',
  subsets: ['latin'],
  variable: "--font-fredoka",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ------------------------------- HeroUI Setup ---------------------------------
import { create } from 'zustand'
import { Providers } from "./providers";

// Create a Zustand store for theme management
export const theme = create((set) => ({
  theme: "light",
  mode: "auto",
  toggleTheme: () => set((state) => ({ theme: state.theme === "light" ? "dark" : "light" })),
  setTheme: (newTheme) => set((state) => ({ theme: newTheme })),
  setMode: (newMode) => set((state) => ({ mode: newMode })),
}))

// -------------------------------- Component layout --------------------------------
import Header from "@/components/header/page";
import Footer from "@/components/footer/page";
import AOSInit from "@/components/animate/AOSInit";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${theme} ${fredoka.className} antialiased`}
      >
        <Providers>
          <AOSInit />
          <Header />
          {children}
          <Footer />
          {/* <ScrollToTopButton /> */}
        </Providers>
      </body>
    </html>
  );
}
